services:
  postgres:
    image: postgres:16
    container_name: postgres_radical
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: radical
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: api_radical
    depends_on:
      - postgres
    environment:
      DB_USER: admin
      DB_PASS: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: radical
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

volumes:
  postgres_data:
